#!/bin/bash

# About Us API Testing Commands
# Replace <YOUR_ADMIN_TOKEN> with your actual admin JWT token
# Replace <BASE_URL> with your API base URL (e.g., http://localhost:8050/api/v1)

BASE_URL="http://localhost:8050/api/v1"
ADMIN_TOKEN="<YOUR_ADMIN_TOKEN>"

echo "=========================================="
echo "About Us API Testing Commands"
echo "=========================================="
echo ""

# ==========================================
# PUBLIC API (No Authentication Required)
# ==========================================

echo "# 1. GET About Us Page Content (Public)"
echo "curl -X GET \\"
echo "  ${BASE_URL}/about-us \\"
echo "  -H 'Content-Type: application/json'"
echo ""

# ==========================================
# ADMIN APIs (Require Admin Authentication)
# ==========================================

echo "# 2. GET About Us Page Content (Admin)"
echo "curl -X GET \\"
echo "  ${BASE_URL}/admin/about-us \\"
echo "  -H 'Authorization: Bearer ${ADMIN_TOKEN}' \\"
echo "  -H 'Content-Type: application/json'"
echo ""

echo "# 3. CREATE/UPDATE About Us Page (POST - Full Update)"
echo "curl -X POST \\"
echo "  ${BASE_URL}/admin/about-us \\"
echo "  -H 'Authorization: Bearer ${ADMIN_TOKEN}' \\"
echo "  -F 'banner_image=@/path/to/banner.jpg' \\"
echo "  -F 'meet_brains_main_image=@/path/to/meet-brains.jpg' \\"
echo "  -F 'banner_banner_title_en=Welcome to Our Company' \\"
echo "  -F 'banner_banner_title_nl=Welkom bij ons bedrijf' \\"
echo "  -F 'banner_banner_subtitle_en=We are passionate about innovation' \\"
echo "  -F 'banner_banner_button_text_en=Learn More' \\"
echo "  -F 'banner_banner_button_link=https://example.com' \\"
echo "  -F 'founderQuote_founder_quote_text_en=Innovation drives everything we do' \\"
echo "  -F 'founderQuote_founder_name_en=John Doe' \\"
echo "  -F 'founderQuote_founder_designation_en=CEO & Founder' \\"
echo "  -F 'founderQuote_note_en=This is a note about the founder' \\"
echo "  -F 'meetBrains_meet_brains_title_en=Meet Our Team' \\"
echo "  -F 'meetBrains_meet_brains_subtitle_en=The brilliant minds behind our success' \\"
echo "  -F 'timeline_timeline_section_title_en=Our Journey' \\"
echo "  -F 'timeline_timeline_section_description_en=Key milestones in our history' \\"
echo "  -F 'timeline_timeline_events_0_year=2020' \\"
echo "  -F 'timeline_timeline_events_0_title_en=Company Founded' \\"
echo "  -F 'timeline_timeline_events_0_description_en=We started our journey' \\"
echo "  -F 'timeline_timeline_events_0_order=1' \\"
echo "  -F 'timeline_timeline_events_1_year=2022' \\"
echo "  -F 'timeline_timeline_events_1_title_en=First Major Milestone' \\"
echo "  -F 'timeline_timeline_events_1_description_en=Reached 1000 customers' \\"
echo "  -F 'timeline_timeline_events_1_order=2' \\"
echo "  -F 'people_title_en=Our People' \\"
echo "  -F 'people_subtitle_en=Meet the amazing team'"
echo ""

echo "# 4. UPDATE About Us Page (PUT - Full Update)"
echo "curl -X PUT \\"
echo "  ${BASE_URL}/admin/about-us \\"
echo "  -H 'Authorization: Bearer ${ADMIN_TOKEN}' \\"
echo "  -F 'banner_image=@/path/to/banner.jpg' \\"
echo "  -F 'banner_banner_title_en=Updated Welcome Message' \\"
echo "  -F 'banner_banner_subtitle_en=Updated subtitle'"
echo ""

echo "# 5. UPDATE Banner Section Only (PATCH)"
echo "curl -X PATCH \\"
echo "  ${BASE_URL}/admin/about-us/sections/banner \\"
echo "  -H 'Authorization: Bearer ${ADMIN_TOKEN}' \\"
echo "  -F 'banner_image=@/path/to/new-banner.jpg' \\"
echo "  -F 'banner_title_en=New Banner Title' \\"
echo "  -F 'banner_title_nl=Nieuwe Banner Titel' \\"
echo "  -F 'banner_subtitle_en=New Banner Subtitle' \\"
echo "  -F 'banner_button_text_en=Click Here' \\"
echo "  -F 'banner_button_link=https://example.com/new-link'"
echo ""

echo "# 6. UPDATE Founder Quote Section Only (PATCH)"
echo "curl -X PATCH \\"
echo "  ${BASE_URL}/admin/about-us/sections/founderQuote \\"
echo "  -H 'Authorization: Bearer ${ADMIN_TOKEN}' \\"
echo "  -F 'founder_quote_text_en=New quote from founder' \\"
echo "  -F 'founder_quote_text_nl=Nieuwe quote van oprichter' \\"
echo "  -F 'founder_name_en=Jane Smith' \\"
echo "  -F 'founder_designation_en=CTO & Co-Founder' \\"
echo "  -F 'note_en=Updated note about the founder'"
echo ""

echo "# 7. UPDATE Meet Brains Section Only (PATCH)"
echo "curl -X PATCH \\"
echo "  ${BASE_URL}/admin/about-us/sections/meetBrains \\"
echo "  -H 'Authorization: Bearer ${ADMIN_TOKEN}' \\"
echo "  -F 'meet_brains_main_image=@/path/to/new-image.jpg' \\"
echo "  -F 'meet_brains_title_en=Meet Our Brilliant Team' \\"
echo "  -F 'meet_brains_subtitle_en=The experts behind innovation'"
echo ""

echo "# 8. UPDATE Timeline Section Only (PATCH)"
echo "curl -X PATCH \\"
echo "  ${BASE_URL}/admin/about-us/sections/timeline \\"
echo "  -H 'Authorization: Bearer ${ADMIN_TOKEN}' \\"
echo "  -F 'timeline_section_title_en=Our History' \\"
echo "  -F 'timeline_section_description_en=Important moments in our journey' \\"
echo "  -F 'timeline_events_0_year=2019' \\"
echo "  -F 'timeline_events_0_title_en=Idea Conception' \\"
echo "  -F 'timeline_events_0_description_en=The idea was born' \\"
echo "  -F 'timeline_events_0_order=0' \\"
echo "  -F 'timeline_events_1_year=2020' \\"
echo "  -F 'timeline_events_1_title_en=Company Founded' \\"
echo "  -F 'timeline_events_1_description_en=Official launch' \\"
echo "  -F 'timeline_events_1_order=1' \\"
echo "  -F 'timeline_events_2_year=2023' \\"
echo "  -F 'timeline_events_2_title_en=Major Expansion' \\"
echo "  -F 'timeline_events_2_description_en=Expanded to 10 countries' \\"
echo "  -F 'timeline_events_2_order=2'"
echo ""

echo "# 9. UPDATE People Section Only (PATCH)"
echo "curl -X PATCH \\"
echo "  ${BASE_URL}/admin/about-us/sections/people \\"
echo "  -H 'Authorization: Bearer ${ADMIN_TOKEN}' \\"
echo "  -F 'title_en=Our Amazing Team' \\"
echo "  -F 'title_nl=Ons Geweldige Team' \\"
echo "  -F 'subtitle_en=Meet the people who make it happen' \\"
echo "  -F 'subtitle_nl=Ontmoet de mensen die het mogelijk maken'"
echo ""

echo "# 10. DELETE About Us Page (Soft Delete)"
echo "curl -X DELETE \\"
echo "  ${BASE_URL}/admin/about-us \\"
echo "  -H 'Authorization: Bearer ${ADMIN_TOKEN}' \\"
echo "  -H 'Content-Type: application/json'"
echo ""

echo "# =========================================="
echo "# JSON Format Examples (Alternative to Form-Data)"
echo "# =========================================="
echo ""

echo "# 11. CREATE/UPDATE About Us Page (POST - JSON Format)"
echo "curl -X POST \\"
echo "  ${BASE_URL}/admin/about-us \\"
echo "  -H 'Authorization: Bearer ${ADMIN_TOKEN}' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"banner\": {"
echo "      \"banner_image\": {"
echo "        \"type\": \"image\","
echo "        \"url\": \"https://example.com/banner.jpg\","
echo "        \"alt\": {"
echo "          \"en\": \"Banner image\""
echo "        }"
echo "      },"
echo "      \"banner_title\": {"
echo "        \"en\": \"Welcome to Our Company\","
echo "        \"nl\": \"Welkom bij ons bedrijf\""
echo "      },"
echo "      \"banner_subtitle\": {"
echo "        \"en\": \"We are passionate about innovation\","
echo "        \"nl\": \"We zijn gepassioneerd over innovatie\""
echo "      },"
echo "      \"banner_button_text\": {"
echo "        \"en\": \"Learn More\","
echo "        \"nl\": \"Meer Weten\""
echo "      },"
echo "      \"banner_button_link\": \"https://example.com\""
echo "    },"
echo "    \"founderQuote\": {"
echo "      \"founder_quote_text\": {"
echo "        \"en\": \"Innovation drives everything we do\","
echo "        \"nl\": \"Innovatie drijft alles wat we doen\""
echo "      },"
echo "      \"founder_name\": {"
echo "        \"en\": \"John Doe\","
echo "        \"nl\": \"Jan Janssen\""
echo "      },"
echo "      \"founder_designation\": {"
echo "        \"en\": \"CEO & Founder\","
echo "        \"nl\": \"CEO & Oprichter\""
echo "      },"
echo "      \"note\": {"
echo "        \"en\": \"This is a note about the founder\""
echo "      }"
echo "    },"
echo "    \"meetBrains\": {"
echo "      \"meet_brains_title\": {"
echo "        \"en\": \"Meet Our Team\","
echo "        \"nl\": \"Ontmoet Ons Team\""
echo "      },"
echo "      \"meet_brains_subtitle\": {"
echo "        \"en\": \"The brilliant minds behind our success\""
echo "      },"
echo "      \"meet_brains_main_image\": {"
echo "        \"type\": \"image\","
echo "        \"url\": \"https://example.com/team.jpg\""
echo "      }"
echo "    },"
echo "    \"timeline\": {"
echo "      \"timeline_section_title\": {"
echo "        \"en\": \"Our Journey\""
echo "      },"
echo "      \"timeline_section_description\": {"
echo "        \"en\": \"Key milestones in our history\""
echo "      },"
echo "      \"timeline_events\": ["
echo "        {"
echo "          \"year\": \"2020\","
echo "          \"title\": {"
echo "            \"en\": \"Company Founded\""
echo "          },"
echo "          \"description\": {"
echo "            \"en\": \"We started our journey\""
echo "          },"
echo "          \"order\": 1"
echo "        },"
echo "        {"
echo "          \"year\": \"2022\","
echo "          \"title\": {"
echo "            \"en\": \"First Major Milestone\""
echo "          },"
echo "          \"description\": {"
echo "            \"en\": \"Reached 1000 customers\""
echo "          },"
echo "          \"order\": 2"
echo "        }"
echo "      ]"
echo "    },"
echo "    \"people\": {"
echo "      \"title\": {"
echo "        \"en\": \"Our People\""
echo "      },"
echo "      \"subtitle\": {"
echo "        \"en\": \"Meet the amazing team\""
echo "      }"
echo "    }"
echo "  }'"
echo ""

echo "# 12. UPDATE Banner Section (PATCH - JSON Format)"
echo "curl -X PATCH \\"
echo "  ${BASE_URL}/admin/about-us/sections/banner \\"
echo "  -H 'Authorization: Bearer ${ADMIN_TOKEN}' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"banner_image\": {"
echo "      \"type\": \"image\","
echo "      \"url\": \"https://example.com/new-banner.jpg\""
echo "    },"
echo "    \"banner_title\": {"
echo "      \"en\": \"New Banner Title\","
echo "      \"nl\": \"Nieuwe Banner Titel\""
echo "    },"
echo "    \"banner_subtitle\": {"
echo "      \"en\": \"New Banner Subtitle\""
echo "    },"
echo "    \"banner_button_text\": {"
echo "      \"en\": \"Click Here\""
echo "    },"
echo "    \"banner_button_link\": \"https://example.com/new-link\""
echo "  }'"
echo ""

echo "# =========================================="
echo "# Notes:"
echo "# =========================================="
echo "# 1. Replace <YOUR_ADMIN_TOKEN> with actual admin JWT token"
echo "# 2. Replace <BASE_URL> with your API base URL"
echo "# 3. For file uploads, use -F flag with @path/to/file"
echo "# 4. For JSON, use -d flag with JSON string"
echo "# 5. Form-data fields use underscore notation (e.g., banner_banner_title_en)"
echo "# 6. JSON format uses nested objects"
echo "# 7. All admin routes require Bearer token authentication"
echo "# 8. Public route (/about-us) does not require authentication"
echo ""

