services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.node
    image: viteezy-node
    container_name: viteezy_node
    ports:
      - "8050:8050"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    image: viteezy-python
    container_name: viteezy_python
    ports:
      - "8000:8000"
    environment:
      - PYTHON_ENV=production
    restart: unless-stopped