import { Router } from "express";
import authRoutes from "./authRoutes";
import userRoutes from "./userRoutes";
import exampleRoutes from "./exampleRoutes";
import paymentRoutes from "./paymentRoutes";
import blogRoutes from "./blogRoutes";
import addressRoutes from "./addressRoutes";
import productRoutes from "./productRoutes";
import productIngredientRoutes from "./productIngredientRoutes";
import productTestimonialRoutes from "./productTestimonialRoutes";
import cartRoutes from "./cartRoutes";
import faqRoutes from "./faqRoutes";
import wishlistRoutes from "./wishlistRoutes";
import orderRoutes from "./orderRoutes";
import couponRoutes from "./couponRoutes";
import couponUsageHistoryRoutes from "./couponUsageHistoryRoutes";
import referralRoutes from "./referralRoutes";
import deliveryPostponementRoutes from "./deliveryPostponementRoutes";
import preCheckoutRoutes from "./preCheckoutRoutes";
import checkoutRoutes from "./checkoutRoutes";
import savedCardRoutes from "./savedCardRoutes";
import subscriptionRoutes from "./subscriptionRoutes";
import membershipRoutes from "./membershipRoutes";
import reviewRoutes from "./reviewRoutes";
import adminMembershipPlanRoutes from "./adminMembershipPlanRoutes";
import adminProductIngredientRoutes from "./adminProductIngredientRoutes";
import adminBlogCategoryRoutes from "./adminBlogCategoryRoutes";
import adminBlogRoutes from "./adminBlogRoutes";
import adminBlogBannerRoutes from "./adminBlogBannerRoutes";
import adminFaqCategoryRoutes from "./adminFaqCategoryRoutes";
import adminFaqRoutes from "./adminFaqRoutes";
import adminCouponRoutes from "./adminCouponRoutes";
import adminDashboardRoutes from "./adminDashboardRoutes";
import adminProductTestimonialRoutes from "./adminProductTestimonialRoutes";
import adminUserRoutes from "./adminUserRoutes";
import adminOrderRoutes from "./adminOrderRoutes";
import adminGeneralSettingsRoutes from "./adminGeneralSettingsRoutes";
import adminProductCategoryRoutes from "./adminProductCategoryRoutes";
import adminLandingPageRoutes from "./adminLandingPageRoutes";
import adminStaticPageRoutes from "./adminStaticPageRoutes";
import adminProductFaqRoutes from "./adminProductFaqRoutes";
import adminTeamMemberRoutes from "./adminTeamMemberRoutes";
import adminAboutUsRoutes from "./adminAboutUsRoutes";
import adminOurTeamPageRoutes from "./adminOurTeamPageRoutes";
import memberRoutes from "./memberRoutes";
import ourTeamPageRoutes from "./ourTeamPageRoutes";
import dashboardRoutes from "./dashboardRoutes";
import landingPageRoutes from "./landingPageRoutes";
import aboutUsRoutes from "./aboutUsRoutes";
import teamMemberRoutes from "./teamMemberRoutes";
import countryRoutes from "./countryRoutes";
import stateRoutes from "./stateRoutes";
import generalSettingsRoutes from "./generalSettingsRoutes";

const router = Router();

// API Routes
router.use("/auth", authRoutes);
router.use("/users", userRoutes);

router.use("/admin/membership-plans", adminMembershipPlanRoutes);
router.use("/admin/product-ingredients", adminProductIngredientRoutes);
router.use("/admin/blog-categories", adminBlogCategoryRoutes);
router.use("/admin/blogs", adminBlogRoutes);
router.use("/admin/blog-banners", adminBlogBannerRoutes);
router.use("/admin/faq-categories", adminFaqCategoryRoutes);
router.use("/admin/faqs", adminFaqRoutes);
router.use("/admin/coupons", adminCouponRoutes);
router.use("/admin/dashboard", adminDashboardRoutes);
router.use("/admin/product-testimonials", adminProductTestimonialRoutes);
router.use("/admin/users", adminUserRoutes);
router.use("/admin/orders", adminOrderRoutes);
router.use("/admin/general-settings", adminGeneralSettingsRoutes);
router.use("/admin/product-categories", adminProductCategoryRoutes);
router.use("/admin/landing-pages", adminLandingPageRoutes);
router.use("/admin/static-pages", adminStaticPageRoutes);
router.use("/admin/product-faqs", adminProductFaqRoutes);
router.use("/admin/team-members", adminTeamMemberRoutes);
router.use("/admin/about-us", adminAboutUsRoutes);
router.use("/admin/our-team-page", adminOurTeamPageRoutes);

router.use("/members", memberRoutes);
router.use("/examples", exampleRoutes);
router.use("/payments", paymentRoutes);
router.use("/blogs", blogRoutes);
router.use("/faqs", faqRoutes);
router.use("/landing-page", landingPageRoutes);
router.use("/about-us", aboutUsRoutes);
router.use("/team-members", teamMemberRoutes);
router.use("/our-team-page", ourTeamPageRoutes);
router.use("/wishlist", wishlistRoutes);
router.use("/addresses", addressRoutes);
router.use("/products", productRoutes);
router.use("/product-ingredients", productIngredientRoutes);
router.use("/product-testimonials", productTestimonialRoutes);
router.use("/carts", cartRoutes);
router.use("/orders", orderRoutes);
router.use("/coupons", couponRoutes);
router.use("/coupon-usage-history", couponUsageHistoryRoutes);
router.use("/referrals", referralRoutes);
router.use("/postponements", deliveryPostponementRoutes);
router.use("/pre-checkout", preCheckoutRoutes);
router.use("/checkout", checkoutRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/saved-cards", savedCardRoutes);
router.use("/subscriptions", subscriptionRoutes);
router.use("/memberships", membershipRoutes);
router.use("/reviews", reviewRoutes);
router.use("/countries", countryRoutes);
router.use("/states", stateRoutes);
router.use("/general-settings", generalSettingsRoutes);

export default router;
